@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUyMTEwNzg3LCJleHAiOjE3NTIxMTQzODcsIm5iZiI6MTc1MjExMDc4NywiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.11opMW6iMIqAYJhPE2JyJE1doF1EGM4A0AdNea6hVfY

###
# Login admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###
# Login user
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "userbaru3@example.com",
    "password": "Password123"
}

###
# Get All users
GET http://localhost:8080/api/admin/users HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Get User by ID
GET http://localhost:8080/api/admin/users/3 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

