@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxNzg0MjQ2LCJleHAiOjE3NTE3ODc4NDYsIm5iZiI6MTc1MTc4NDI0NiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.3unH_8qqsWpxPHj2-brskKIa-Hd3lo1H4q0dD4cqrKA

###
# Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "User Baru 3",
    "email": "userbaru3@example.com",
    "password": "password123",
    "password_confirmation": "password123"
}

###
# Login admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###
# Login user
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "userbaru3@example.com",
    "password": "password123"
}

###
# Logout
GET http://localhost:8080/api/auth/logout HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Get Profile user
GET http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Put Profile user (update profil penuh)
PUT http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nama Baru Pengguna",
    "email": "email_baru@example.com"
}

###
# Patch Profile user (update profil parsial)
PATCH http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Hanya Nama yang Berubah"
}

### Get All User Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Create New Task
POST http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Belajar Laravel",
    "description": "Selesaikan tutorial Laravel sampai tuntas.",
    "status": "in-progress",
    "due_date": "2025-07-31 18:00:00"
}

###
# Test
GET http://localhost:8080/api/protected/test HTTP/1.1
Content-Type: application/json
