@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InVzZXJiYXJ1M0BleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUxOTUzMzA5LCJleHAiOjE3NTE5NTY5MDksIm5iZiI6MTc1MTk1MzMwOSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.5bqKogqLYtgJzjLA7ebKEQh7brBfZ2s_1J5zj1FiIT4

###
# Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "User Baru 3",
    "email": "userbaru3@example.com",
    "password": "password123",
    "password_confirmation": "password123"
}

###
# Login admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###
# Login user
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "userbaru3@example.com",
    "password": "Password123"
}

###
# Logout
GET http://localhost:8080/api/auth/logout HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Get Profile user
GET http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Put Profile user (update profil penuh)
PUT http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nama Baru Pengguna",
    "email": "email_baru@example.com"
}

###
# Patch Profile user (update profil parsial)
PATCH http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Hanya Nama yang Berubah"
}

###
# Put User Password
PUT http://localhost:8080/api/profile/password HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "old_password": "password123",
    "new_password": "Password123",
    "confirm_password": "Password123"
}

###
# Test
GET http://localhost:8080/api/protected/test HTTP/1.1
Content-Type: application/json
