@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzUxODE3OTc5LCJleHAiOjE3NTE4MjE1NzksIm5iZiI6MTc1MTgxNzk3OSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.qboJBoKJRB6eRITKednuPcn13LW2jDpLqeX6bp7Nsko

###
# Register
POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
    "name": "User Baru 3",
    "email": "userbaru3@example.com",
    "password": "password123",
    "password_confirmation": "password123"
}

###
# Login admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###
# Login user
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "userbaru3@example.com",
    "password": "password123"
}

###
# Logout
GET http://localhost:8080/api/auth/logout HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Get Profile user
GET http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Put Profile user (update profil penuh)
PUT http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Nama Baru Pengguna",
    "email": "email_baru@example.com"
}

###
# Patch Profile user (update profil parsial)
PATCH http://localhost:8080/api/profile HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "Hanya Nama yang Berubah"
}

###
# Test
GET http://localhost:8080/api/protected/test HTTP/1.1
Content-Type: application/json
