@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxMCwiZW1haWwiOiJzYWZpcmFAZXhhbXBsZS5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc1MjQwODMxOSwiZXhwIjoxNzUyNDExOTE5LCJuYmYiOjE3NTI0MDgzMTksImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC8ifQ.mgBpUkq4m9BU51cXqoYHmUfzahhe2thvilPxJCaYDLw

###
# Login admin
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "password"
}

###
# Login user
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "safira@example.com",
    "password": "Password123"
}

### Get All User Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Create New Task
POST http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Belajar Javascript",
    "description": "Selesaikan tutorial Javascript sampai tuntas.",
    "status": "in-progress",
    "due_date": "2025-07-31 18:00:00"
}

### Get Task by ID
GET http://localhost:8080/api/tasks/8
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Put Task (update full task)
PUT http://localhost:8080/api/tasks/8 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Belajar ExpressJS",
    "description": "Selesaikan tutorial ExpressJS sampai tuntas.",
    "status": "in-progress",
    "due_date": "2025-07-31 18:00:00"
}

###
# Patch Task (update task parsial)
PATCH http://localhost:8080/api/tasks/8 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "status": "completed"
}

###
# Delete Task 
DELETE http://localhost:8080/api/tasks/6 HTTP/1.1
Authorization: Bearer {{accessToken}}
