@accessToken = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJlbWFpbCI6InVzZXJiYXJ1M0BleGFtcGxlLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzUxODgxNzcxLCJleHAiOjE3NTE4ODUzNzEsIm5iZiI6MTc1MTg4MTc3MSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwLyJ9.994SQUOWkdKl7JaxaGG___dA7zCatDGnCf0qSSMJvHg

### Get All User Tasks
GET http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Create New Task
POST http://localhost:8080/api/tasks
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Belajar Laravel",
    "description": "Selesaikan tutorial Laravel sampai tuntas.",
    "status": "in-progress",
    "due_date": "2025-07-31 18:00:00"
}

### Get Task by ID
GET http://localhost:8080/api/tasks/8
Authorization: Bearer {{accessToken}}
Content-Type: application/json

###
# Put Task (update full task)
PUT http://localhost:8080/api/tasks/8 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Belajar ExpressJS",
    "description": "Selesaikan tutorial ExpressJS sampai tuntas.",
    "status": "in-progress",
    "due_date": "2025-07-31 18:00:00"
}

###
# Patch Task (update task parsial)
PATCH http://localhost:8080/api/tasks/8 HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "status": "completed"
}